title: Grainsizetools script
description: A Python script for estimating the grain size from thin sections
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
